---
- hosts: redhathosts
  become: yes
  tasks:
  - name: install apache2(webserver) on ubuntu node
    apt:
     name: apache2
     state: present
  - name: service restart ubuntu
    service:
     name: apache2
     state: started
  - name: install httpd(web server) on redhat
    yum:
     name: httpd
     state: present
  - name: service restart redhat
    service:
     name: httpd
     state: started