---
- hosts: all
  become: yes
  tasks:
  - name: install apache2 on node
    apt:
     name: apache2
     state: present
  - name: service restart
    service:
     name: apache2
     state: restarted