---
- hosts: webservers
  become: yes
  tasks:
  - name: webserver install on ubuntu
    apt:
     name: "{{webserveronubuntu}}"
     state: present
    when: ansible_os_family== "Debian"

  - name: webserver start on ubuntu
    service:
     name: "{{webserveronubuntu}}"
     state: restarted
    when: ansible_os_family== "Debian"

  - name: webserver install on redhat
    yum:
     name: "{{webserveronredhat}}"
     state: present
    when: ansible_os_family== "RedHat"   
    
  - name: webserver start on redhat
    service:
     name: "{{webserveronredhat}}"
     state: restarted
    when: ansible_os_family== "RedHat" 